export interface OsmSpouseDetail {
    id: string;
    citizen_id?: string | null;
    prefix_id?: string | null;
    prefix_name_th?: string | null;
    first_name: string;
    last_name: string;
    phone?: string | null;
    email?: string | null;
    profile_image?: string | null;
    gender?: string | null;
    birth_date?: string | null;
    occupation_id?: string | null;
    occupation_name_th?: string | null;
    education_id?: string | null;
    education_name_th?: string | null;
    blood_type?: string | null;
    address_number?: string | null;
    alley?: string | null;
    street?: string | null;
    village_no?: string | null;
    village_name?: string | null;
    village_code?: string | null;
    province_id?: string | null;
    province_name_th?: string | null;
    district_id?: string | null;
    district_name_th?: string | null;
    subdistrict_id?: string | null;
    subdistrict_name_th?: string | null;
    postal_code?: string | null;
}

export interface OsmChildDetail extends OsmSpouseDetail {
    order_of_children?: number | null;
}

export interface OsmProfileDetail {
    id: string;
    citizen_id?: string | null;
    prefix_id?: string | null;
    prefix_name_th?: string | null;
    first_name: string;
    last_name: string;
    phone?: string | null;
    email?: string | null;
    gender?: string | null;
    osm_year?: number | null;
    birth_date?: string | null;
    marital_status?: string | null;
    number_of_children?: number | null;
    occupation_id?: string | null;
    occupation_name_th?: string | null;
    education_id?: string | null;
    education_name_th?: string | null;
    blood_type?: string | null;
    health_service_id?: string | null;
    health_service_name_th?: string | null;
    bank_id?: string | null;
    bank_name_th?: string | null;
    bank_account_number?: string | null;
    volunteer_status?: string | null;
    is_smartphone_owner?: boolean;
    address_number?: string | null;
    alley?: string | null;
    street?: string | null;
    village_no?: string | null;
    village_name?: string | null;
    village_code?: string | null;
    province_id?: string | null;
    province_name_th?: string | null;
    district_id?: string | null;
    district_name_th?: string | null;
    subdistrict_id?: string | null;
    subdistrict_name_th?: string | null;
    postal_code?: string | null;
    is_active: boolean;
    approval_status?: string | null;
    osm_code?: string | null;
    osmCode?: string | null;
    osm_showbbody?: string | null;
    showbody?: string | null;
    osm_status?: string | null;
    new_registration_allowance_status?: string | null;
    profile_image?: string | null;
    approval_by?: string | null;
    approval_date?: string | null;
    approval_by_name?: string | null;
    approval_by_position_name?: string | null;
    approval_by_scope_level?: string | null;
    approval_by_scope_label?: string | null;
    created_by?: string | null;
    updated_by?: string | null;
    created_by_name?: string | null;
    updated_by_name?: string | null;
    created_by_position_name?: string | null;
    created_by_scope_level?: string | null;
    created_by_scope_label?: string | null;
    updated_by_position_name?: string | null;
    updated_by_scope_level?: string | null;
    updated_by_scope_label?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
    spouse?: OsmSpouseDetail | null;
    children?: OsmChildDetail[];
}
