export interface YuwaOsmDetail {
    id: string;
    citizen_id?: string | null;
    yuwa_osm_code?: string | null;
    phone_number: string;
    first_name: string;
    last_name: string;
    gender?: string | null;
    email?: string | null;
    line_id?: string | null;
    school?: string | null;
    organization?: string | null;
    province_code?: string | null;
    province_name?: string | null;
    district_code?: string | null;
    district_name?: string | null;
    subdistrict_code?: string | null;
    subdistrict_name?: string | null;
    profile_image?: string | null;
    registration_reason?: string | null;
    birthday?: string | null;
    is_active: boolean;
    approval_status: string;
    approved_by?: string | null;
    approved_at?: string | null;
    approved_by_name?: string | null;
    approved_by_position_name?: string | null;
    approved_by_scope_level?: string | null;
    approved_by_scope_label?: string | null;
    rejected_by?: string | null;
    rejected_by_name?: string | null;
    rejected_by_position_name?: string | null;
    rejected_by_scope_level?: string | null;
    rejected_by_scope_label?: string | null;
    rejected_at?: string | null;
    rejection_reason?: string | null;
    people_id?: string | null;
    source_people_id?: string | null;
    transferred_by?: string | null;
    transferred_at?: string | null;
    created_at?: string | null;
    updated_at?: string | null;
}
